In [1]:
import numpy as np
from numpy.linalg import eig

1. Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

In [2]:
A1 = np.array([[-1,-6],[2,6]])
A1

array([[-1, -6],
       [ 2,  6]])

In [3]:
w1, v1 = eig(A1)

In [4]:
print(f'Собственное значение: {w1}')

Собственное значение: [2. 3.]


In [5]:
print(f'Собственные векторы: {v1}')

Собственные векторы: [[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]


2. Дан оператор поворота на 180 градусов, задаваемый матрицей

In [6]:
A2 = np.array([[-1, 0],[0 ,-1]])

In [7]:
w2, v2 = eig(A2)

In [8]:
v2

array([[1., 0.],
       [0., 1.]])

####  Значение собственного вектора = отрицательному значению матрицы => любой  вектор будет коллинеарным => собственным.

3. Пусть линейный оператор задан матрицей [1,1],[-1,3]. Установить, является ли вектор  x=(1,1)  собственным вектором этого линейного оператора.

In [9]:
A3 = np.array([[1,1],[-1,3]])
A3

array([[ 1,  1],
       [-1,  3]])

A3_1 = A3*x = (1+1,-1+3) = (2, 2)

## Ответ:
#### Вектор х= (1, 1) является собственным вектором линейного оператора. λ  = 2

4. Пусть линейный оператор задан матрицей. Установить, является ли вектор  x=(3,−3,−4)  собственным вектором этого линейного оператора.

In [10]:
A4 = np.array([[0,3,0],[3,0,0],[0,0,3]])

In [11]:
A4

array([[0, 3, 0],
       [3, 0, 0],
       [0, 0, 3]])

A4_1 = A4*x =(0+9+0, -9+0+0, 0+0+12) = (9, -9, 12)

### Ответ
#### x=(3,−3,−4)  не является собственным вектором этого линейного оператора.